### ISSUE TITLE
links to your wiki are borked

### ISSUE THREAD

**Issue by jeremymeyers** [obahareth/my-mac-os#5]
for example visual studio goes to https://wiki.omar.engineer/vscode/extensions when should go to https://wiki.omar.engineer/apps-and-tools/visual-studio-code/extensions#utility

(i'm sure this isn't high priority just wanted to note that it was happening since you updated your wiki)

**Comment by obahareth** [comment]
Thanks for letting me know @jeremymeyers, I'll fix them!
